name: kgraphmemory
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - pip:
    - vital-ai-vitalsigns>=0.1.32
    - vital-ai-domain>=0.1.7
    - six
    - pyyaml
    - vital-ai-haley-kg>=0.1.24
    - rdflib>=7.0.0
    - SPARQLWrapper>=2.0.0
    - networkx
    - matplotlib
    - kgraphservice>=0.0.8
    - scikit-learn
    - scipy
    - numpy
    - pyoxigraph>=0.4.11
    - qdrant-client
    - protobuf>=5.29.0,<6.0.0
